git info improved

diff --git a/linux b/linux
--- a/linux
+++ b/linux
@@ -807,6 +807,9 @@ int main(int argc, char** argv)
       #<enter>: go to link under cursor
       #<tab>: go to next link
       #1-9: go to menu item nb.
+      #m: select menu item in current page by name.
+        #can tab complete.
+        #even without tab complete, goes to first match on enter.
 
     ##node
 
@@ -814,8 +817,14 @@ int main(int argc, char** argv)
       #t: top node
       #[, ]: next previous node. May     change node level.
       #n, p:                         not                   
-      #m: select menu item in current page by name. Can tab complete.
-      #g:                     all                                       
+      #l: go to last viewed node. can be used several times.
+      #g: like m, but search all nodes
+
+    ##search
+
+      #/: regex
+      #{: next      match of previous search
+      #}: previous
   
   info
   info rm
@@ -1376,6 +1385,14 @@ int main(int argc, char** argv)
     #concurrence to imagemagick, supposedly faster. c++ template api
 
     sudo aptitude install -y exactimage
+
+  ##dvipng
+
+    #convert dvi to png
+
+    #important application: latex -> dvi -> png -> website.
+
+    sudo aptitude install -y dvipng
 
 ##book
 
@@ -2072,6 +2089,17 @@ int main(int argc, char** argv)
 
     ##libs
 
+      ##itro
+
+        #**TO USE A LIBRARY YOU NEED 2 THINGS**:
+
+        #- the header .h file(s)
+        #- the compiled .so or .a file(s)
+
+        #either those must be in you compiler find path
+        #(different for headers and compiled files)
+        #or you must explicitly add them to the path.
+
       ##search path
       
         #where gcc search path for .a and .so
@@ -2366,130 +2394,6 @@ int main(int argc, char** argv)
           file -L /lib/ld-linux.so.2
             #ELF
       
-      ##recommended libs
-
-        #this is just a quick list, installation and cheats will go better
-        #in other files/dirs
-
-        ##performance note
-              
-          #to get the most out of applications, you have to
-          #compile it on your own computer so that the compiler will
-          #be able to make all the possible optimizations for your given
-          #architecture.
-      
-        ##c
-          
-          sudo aptitude install -y linux-source linux-headers 
-
-          ##check
-          
-            #c unit testing
-            
-            sudo aptitude install -y check
-
-          ##ncurses
-          
-            #command line interactive interfaces
-            
-            sudo aptitude install -y ncurses
-
-          ##expat
-          
-            #xml parsing
-          
-          ##to evaluate
-
-            ##PCRE 
-
-              #perl regexes. c11 has regexes.
-            
-            ##popt 
-            
-              #parse command line options
-
-        ##c++
-
-          ##boost
-
-            #cross platform utilities
-            
-            #very popular, largely influences c++ future
-
-        ##glx
-        
-          #interface between opengl and x server
-          
-          #allows x windows to use opengl acceleration
-          
-          #must also support a given opengl version
-          
-          sudo aptitude install -y mesa-utils
-
-          glxinfo | less
-            #lots of opengl info
-          glxgears
-            #demo
-
-        ##scientific
-
-          ##netlib
-
-            #lots of good scientific libs from there
-
-            ##blas lapack
-
-              #langs: fortran (native), c
-
-              #linear algebra. very widely standard..
-
-          ##acts collection
-
-            #<http://acts.nersc.gov/tools.html>
-
-            #collection of good numerical libraries.
-
-            #industry usage.
-            
-          ##opengl glut
-
-            #langs: c++(native), python
-
-            #3d rendering
-
-            #de facto open source standard.
-
-          ##opencv
-
-            #langs: c++(native), python
-          
-            #computer vision
-
-          ##gsl
-
-
-            #langs: c, c++
-          
-            #lots of domains
-
-          ##freefem
-          
-            #2d and 3d fem
-            
-            #TODO
-          
-          ##r
-          
-            #statistics
-            
-          ##it++
-          
-            #signal processing
-
-          ##ode
-          
-            #rigid body physics engine
-        
     ##gdb
     
       #gnu symbolic debugger
@@ -4302,270 +4206,6 @@ int main(void)
       #convert contents of F from BIG-FIVE to UTF-8
       #no changes made: only outputs to stdout
 
-##mysql
-
-  ##souces
-
-    #best way to get started: <http://www.w3schools.com/sql/>
-    #<http://www.pantz.org/software/mysql/mysqlcommands.html >
-
-  ##intro
-
-    #mysql is a database that runs on a server.
-    
-    #this means that requests are made to the server,
-    #and the server returns responses.
-    
-    #to install the sever see <#mysql server>.
-
-  ##mysql server
-
-    sudo aptitude install -y mysql-server
-      #he will ask you for the password, fill it in
-      #mysql -u root #the tutorial said do that, but I didn't need to. This would be for the password.
-
-    #configuration file:
-      less /etc/mysql/my.cnf
-    #contains info such as: listen port, ...
-  
-  ##interfaces
-    
-    ##mysql command
-
-      #the `mysql` executable is a simple text based interface to mysql
-
-      #it is bad to view tables that don't fit into the terminal width.
-
-      #one advantage of this interface is the possibilty for automation
-      #using bash. 
-    
-    ##phpmyadmin
-
-      #popular php based broser interface for mysql
-      
-      #first make sure that php is installed. See <#php>.
-
-        sudo aptitude install -y libapache2-mod-auth-mysql php5-mysql phpmyadmin
-        #gksudo gedit /etc/php5/apache2/php.ini
-          #according to tutorial, should uncomment ;extension=mysql.so, but I could not find it in the file. still works.
-
-        sudo vim /etc/apache2/apache2.conf
-        #ensure following line is anywhere in the file:
-          #Include /etc/phpmyadmin/apache.conf
-        sudo service apache2 restart
-
-      #test phpmyadmin and mysql:
-        firefox http://localhost/phpmyadmin &
-      #login: 'root'. password: what you entered at installation.
-
-  ##users
-
-    #mysql has the concept of user permissions.
-
-    #each user/host pair has certain priviledges such as
-    #view, edit, delete databases, tables and entries.
-
-    #those permissions may apply either to specific table/database
-    #or to the entire server (global permissions)
-    
-    #by default, a superuser called root is created during server installation.
-    
-    ##login
-
-      #logs in as user root
-      #and prompts for password:
-        mysql -u root -p
-
-      #execute command and exit:
-        mysql -u root -p -e "create database test;"
-
-      #BAD: unsafe. Logs in without prompting password:
-        mysql -u root -p"pass"
-      #there must be no space between `-p` and `pass`
-
-      #change password for an existing user:
-        mysqladmin -u root -p password
-      #prompts for old and new password
-
-    #list users and their *global* priviledges:
-      select * from mysql.user;
-    #note how priviledges are given to user/host pairs.
-
-    #create a new user:
-      CREATE USER 'newuser'@'localhost' IDENTIFIED BY 'password';
-    #this user has no priviledges
-    
-    #show all global priviledges supported by a server:
-      SHOW PRIVILEGES;
-    
-    #view priviledges given for databases:
-      SHOW GRANTS;
-        #to current user:
-      SHOW GRANTS FOR user@host;
-        #to user:
-  
-    #give priviledges to an user:
-      #*.* implies global priviledges:
-      GRANT ALL            ON *   .*     TO 'user'@'localhost';
-      #all tables on a mydb:
-      GRANT ALL            ON mydb.*     TO 'user'@'localhost';
-      GRANT SELECT, INSERT ON mydb.*     TO 'user'@'localhost';
-      #only for table mydb.mytbl:
-      GRANT ALL            ON mydb.mytbl TO 'user'@'localhost';
-      GRANT SELECT, INSERT ON mydb.mytbl TO 'user'@'localhost';
-      #                       ^^^^ ^^^^^                      
-      #                       1    2                          
-      FLUSH PRIVILEGES;
-    #1: on which databases
-    #2: on which tables of those databases
-
-    #remove priviledges of an user:
-      REVOKE
-
-    #remove users:
-      DROP USER user@localhost, user2@localhost
-
-  ##commands
-  
-    ##databases
-  
-      #list databases:
-        show databases
-
-      #create databases:
-        create database
-        create database elearn_trac character set utf8;
-          #utf8 charset. default is ascii.
-      
-      ##charset and collation
-      
-        ##charset
-
-          #view all possible charsets:
-            show character set;
-
-          #view charset for given db/table/column:
-            #<http://stackoverflow.com/questions/1049728/how-do-i-see-what-character-set-a-database-table-column-is-in-mysql>
-
-        ##collation
-
-          #is how strings in a given charset are compared for equal, smaller, larger.
-          
-          #may be set for entire database, tables or individual columns
-          
-          #examples: case sensitive, case insensitive, Uppercase comes first (ABC...abc)
-          #same order: (AaBbCc...), etc.
-        
-          #view all possible collations for each charset
-            show collation;
-
-      #use a database:
-        use db
-      #necessary before most table operations
-      
-      #list tables of a database:
-        show tables in db
-        show tables
-          #for current db
-
-      #delete a database:
-        drop db
-  
-    ##tables
-
-      #get table description:
-        DESC tbl;
-
-      #get more info on table:
-        show create tbl
-      #shows each step used to create it
-
-      #creates a new table:
-
-      #creates a new table with same structure as old one:
-        CREATE TABLE newtable LIKE $oldtable
-
-      #delete tables:
-        drop table table1, table2;
-
-      #copies data from old table to new table
-        INSERT INTO $newtable SELECT * FROM $oldtable
-
-      #removes all entries from a table
-        TRUNCATE TABLE $tablename
-      #faster than 
-
-      #deletes entire table data. difference from truncate?
-        DELETE FROM $table;
-
-      ##select
-
-        #choose certain entries to do actions on them
-
-        #chose a column:
-          select column from table
-
-        #chose many columns
-          select column1, column2 from table
-
-        #unique entries:
-          select distinct column from table
-        #only shows each value of column once
-
-        #chose all column:
-          select * from table
-
-      ##locks
-
-        #synchronization method
-
-          LOCK TABLES `$table1` READ; `$table2` WRITE;
-          #cannot read from table1 and write to table2
-          #use before making big db changes
-
-          UNLOCK TABLES
-          #releases all locks
-
-  ##column types
-    #length
-    #there are length limitation on *row* size (sum of all columns)
-      #2**16-1 = 8k-1
-      #this means 8k-1/256 = 85 CHAR(256) fields are permitted
-      #TEXT field not stored on the table: each occupies up to 12 bytes on their row
-
-  ##dump (save to file)
-
-    mysqldump -u root "$DB_NAME" > bak.sql
-    mysqldump -u root "$DB_NAME" "$TABLE1" "$TABLE2" > bak.sql
-    #dump to file
-    #no USE
-    #drops existing
-
-    mysqldump -u root --databases "$DB1" "$DB2" > bak.sql
-    #mutiple dbs
-    #creates dbs with old names, uses them
-
-    mysqldump -u root --all-databases > bak.sql
-    #all dbs
-    #with USE, old names
-
-    # -d : no data
-    # --no-create-info : data only
-
-  ###restore
-
-    PASS=
-    mysql-u root -p"$PASS" < bak.sql
-    #make sure the db exists/you want to overwrite it
-
-    DB=
-    DB2=
-    PASS=
-    mysql -u root -p"$PASS" -e "create database $DB2;"
-    mysqldump -u root -p"$PASS" $DB | mysql -u root -p"$PASS" $DB2
-    #make sure the db exists/you want to overwrite it
-    #copy db to new name
-
 ##cron
 
   #you can't launch graphical applications!
@@ -5643,6 +5283,7 @@ int main(void)
 ##files
 
   ##ls
+    #POSIX
   
     #list files in dirs
     
@@ -5710,7 +5351,38 @@ int main(void)
     
       #config <#ls> colors
 
+    ##gnu extensions
+
+      #-R: recursive
+
+        ls -R
+
+  ##tree
+
+    #prints visual file tree
+
+    #install:
+
+      sudo aptitude install tre
+
+    #recurse 2 levels (default infinite):
+
+      tree -L 2
+
+    #-a: include hidden:
+
+      tree -a
+
+    ##--charset
+
+      #select a smaller charset for output:
+
+        tree --charset=ascii
+
+      #this is good if you want to paste output!
+
   ##cd
+    #POSIX
 
     cd dir
       #go to dir
@@ -5739,12 +5411,14 @@ int main(void)
         #~/a
 
   ##touch
+    #POSIX
 
     touch f
       #creates file if does not exist.
       #updates modify date to present if exists
 
   ##mkdir
+    #POSIX
 
     #make a dir
 
@@ -5758,6 +5432,7 @@ int main(void)
       #-m: mode (permissions)
   
   ##mv
+    #POSIX
   
     #move or rename files
     
@@ -5801,6 +5476,7 @@ int main(void)
       assert [ `ls | wc -l` = 2 ]
 
   ##cp
+    #POSIX
 
     #copy
 
@@ -5922,6 +5598,7 @@ int main(void)
       #TODO understand this!
 
   ##chown
+    #POSIX
   
     #change owner and group of files
 
@@ -5956,6 +5633,8 @@ int main(void)
       sudo chown :newgroup
 
   ##chmod
+
+    #POSIX
   
     #change file permissions
 
@@ -6055,6 +5734,8 @@ int main(void)
       #---------
 
   ##stat
+
+    #POSIX
 
     #cli for sys_stat
     
@@ -6163,13 +5844,20 @@ int main(void)
     #compares F and G byte by byte, until first difference
     #if equal, print nothing
       #else, print location of first difference
+    
+    ##-s
 
-    cmp -s "$F" "$G"
-    if [ $? -eq 1 ]; then
-        echo neq
-    else
-        echo eq
-    fi
+      #silent
+      
+      #return status 0 if equal
+      #!= 0 otherwise
+
+        cmp -s "$F" "$G"
+        if [ $? -eq 1 ]; then
+            echo neq
+        else
+            echo eq
+        fi
 
   ##find
 
@@ -8694,13 +8382,19 @@ print "</body></html>"
 
   ##java
 
-    sudo add-apt-repository -y ppa:webupd8team/java
-    sudo aptitude update
-    sudo aptitude install -y oracle-java7-installer
-    sudo aptitude install -y oracle-java7-set-default
-      #set env variables
-    sudo aptitude install -y icedtea6-plugin
+    #its sometimes hard to make this work...
+
+    #not sure which is best
+
+    #sudo add-apt-repository -y ppa:webupd8team/java
+    #sudo aptitude update
+    #sudo aptitude install -y oracle-java7-installer
+    #sudo aptitude install -y oracle-java7-set-default
+      ##set env variables
+    #sudo aptitude install -y icedtea6-plugin
       #allows to run java on certain brosers, including firefox
+
+    sudo aptitude install openjdk-7-jre icedtea-7-plugin
 
   ##perl
   
@@ -9248,6 +8942,142 @@ add Lock = Caps_Lock
     
       ./NVIDIA*.run --extract-only
       vim NVIDIA*/README
+
+##libs
+
+  #this is just a quick list, installation and cheats may go better
+  #in other files/dirs since libs are usually large to understand
+
+  ##performance note
+        
+    #to get the most out of applications, you have to
+    #compile it on your own computer so that the compiler will
+    #be able to make all the possible optimizations for your given
+    #architecture.
+
+  ##c
+    
+    sudo aptitude install -y linux-source linux-headers 
+
+    ##check
+    
+      #c unit testing
+      
+      sudo aptitude install -y check
+
+    ##ncurses
+    
+      #command line interactive interfaces
+      
+      sudo aptitude install -y ncurses
+
+    ##expat
+    
+      #xml parsing
+    
+    ##to evaluate
+
+      ##PCRE 
+
+        #perl regexes. c11 has regexes.
+      
+      ##popt 
+      
+        #parse command line options
+
+  ##c++
+
+    ##boost
+
+      #cross platform utilities
+      
+      #very popular, largely influences c++ future
+
+  ##glx
+  
+    #interface between opengl and x server
+    
+    #allows x windows to use opengl acceleration
+    
+    #must also support a given opengl version
+    
+    sudo aptitude install -y mesa-utils
+
+    glxinfo | less
+      #lots of opengl info
+    glxgears
+      #demo
+
+##scientific
+
+  ##netlib
+
+    #lots of good scientific libs from there
+
+    ##blas lapack
+      #fortran: native
+      #clang:   bindings
+
+      #linear algebra. very widely standard.
+
+  ##acts collection
+
+    #<http://acts.nersc.gov/tools.html>
+
+    #collection of good numerical libraries.
+
+    #- asdf
+    #- qwer
+
+    #industry usage.
+    
+  ##opengl glut
+    #native:   c++
+    #bindings: python
+
+    #adsf
+
+    #3d rendering
+
+    #de facto open source standard.
+
+  ##opencv
+
+    #langs: c++(native), python
+  
+    #computer vision
+
+  ##gsl
+    #c
+    #c++
+
+    #tons of scientific functions
+
+  ##freefem
+  
+    #2d and 3d fem
+    
+    #TODO
+  
+  ##r
+  
+    #statistics
+    
+  ##it++
+  
+    #signal processing
+
+  ##ode
+  
+    #rigid body physics engine
+
+  ##plplot
+    #c
+    #cross platform
+
+    #graph plotting
+
+    #quite good at first sight
 
 ##misc
 
